In [2]:
import numpy as np

In [3]:
ls = [1,2,3]
arr = np.array(ls)
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [6]:
arr.size

3

In [7]:
arr.shape

(3,)

In [13]:
arr = [1,2,3,4.2,5.3]
arr1=np.array(arr)
type(arr1)

numpy.ndarray

In [15]:
np.array([12,3.4,45], dtype = 'str')

array(['12', '3.4', '45'], dtype='<U3')

In [19]:
new_arr=np.array([[12,43,23],
         [22,33,44],
         [55,66,77]])

In [28]:
new_arr1=np.array([[12,43,23],
         [22,33,44]])

In [21]:
new_arr.ndim

2

In [23]:
range(1,11)

range(1, 11)

In [24]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
list(range(1.5,11.5))

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [31]:
new_arr1

array([[12, 43, 23],
       [22, 33, 44]])

In [35]:
new_arr1.reshape(3,2)

array([[12, 43],
       [23, 22],
       [33, 44]])

In [36]:
new_arr1.flatten()

array([12, 43, 23, 22, 33, 44])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.ones([2,3],dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
np.ones([2,3,4]) #3*4 ke 2 matrix

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
np.zeros([2,3,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.full(10,7) #generates 10 elemnets with value 7

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [46]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [47]:
np.full([2,3],[7,8,9])

array([[7, 8, 9],
       [7, 8, 9]])

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(1,10,5) #5 NOS BETWEENA RANGE OF 1 TO 10

array([5, 7, 6, 2, 1], dtype=int32)

In [51]:
np.random.randint(1,10,[3,4])

array([[8, 3, 8, 7],
       [4, 7, 4, 2],
       [3, 4, 5, 3]], dtype=int32)

In [53]:
np.random.rand(5)

array([0.95584871, 0.43183416, 0.29082352, 0.43637977, 0.88062971])

In [57]:
np.random.rand(1,10,5) #shown uniform distribution

array([[[0.24578192, 0.9278377 , 0.42073672, 0.32079336, 0.14952652],
        [0.70889618, 0.21834971, 0.21818965, 0.40922277, 0.48532509],
        [0.02113404, 0.49074274, 0.89318579, 0.56586819, 0.80445417],
        [0.93274613, 0.78481671, 0.85141518, 0.67636615, 0.3761409 ],
        [0.72568825, 0.55349022, 0.40780634, 0.28550269, 0.34090145],
        [0.10500705, 0.16225515, 0.03887909, 0.50860107, 0.71214921],
        [0.87396213, 0.97152896, 0.58326108, 0.11287756, 0.3491116 ],
        [0.33806744, 0.31848443, 0.93580948, 0.86754274, 0.68823436],
        [0.84252212, 0.16908018, 0.05786009, 0.04402222, 0.47137758],
        [0.44085403, 0.66879469, 0.15058307, 0.96693189, 0.6768409 ]]])

In [56]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [60]:
np.linspace(2,5,retstep=True)

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 np.float64(0.061224489795918366))

In [62]:
arr = np.arange(1,11).reshape([2,5])

In [ ]:
#copy array
new_arr = arr.view() #reference is passed
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [64]:
arr[0,0]=100

In [65]:
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [66]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [73]:
new_arr3 = arr.copy() #values are copied
new_arr3

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [74]:
arr[0,0]=1000

In [75]:
new_arr3

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [76]:
arr.T

array([[1000,    6],
       [   2,    7],
       [   3,    8],
       [   4,    9],
       [   5,   10]])